version: '2'
services:
  #服务名称
  influxdb:
    #容器名称
    container_name: influxdb2
    #镜像名称
    image: influxdb
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - 8087:8086
    #挂载
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    networks:
      - net-influxdb2
networks:
  net-influxdb2: