version: '2'
services:
    gitlab:
      image: gitlab/gitlab-ce
      container_name: gitlab
#      hostname: bestsoftware.f3322.net
      restart: always
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.1.10:8880'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.163.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "badevops@163.com"
          gitlab_rails['smtp_password'] = "ODTGLUROBJUSZRPZ"
          gitlab_rails['smtp_domain'] = "smtp.163.com"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = 'badevops@163.com'
          gitlab_rails['initial_root_password'] = '7hqPjm3AuqoCOqNaKm'
      ports:
        - '8880:8880'
#        - '8443:443'
        - '8822:22'
      volumes:
        - ./config:/etc/gitlab
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
