version: "2"
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=P@ssw0rd
    volumes:
      - /docker/mariadb/data:/config
#    ports:
#      - 3306:3306
    restart: unless-stopped
    hostname: mariadb