version: "2"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks
    environment:
      - PASSWORD=KJXutW4cUj
    ports:
      - 18548:8388
      - 18548:8388/udp
    restart: unless-stopped