version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/conf.d:/etc/nginx/conf.d
      - /docker/nginx/html:/usr/share/nginx/html
      - /docker/nginx/log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=asfuyao.f3322.org
      - NGINX_PORT=80
