version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/export/backup/Music:/music:ro"
      
      
docker run -d --name navidrome --restart=unless-stopped --user $(id -u):$(id -g) -v /root/music/music:/music -v /root/music/data:/data -p 4533:4533 -e ND_LOGLEVEL=info deluan/navidrome:latest      