USE [master]
GO
ALTER DATABASE [TZToolDB] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE [TZToolDB] COLLATE Latin1_General_CI_AS
GO

USE [master]
GO

ALTER DATABASE [TZToolDB] SET  multi_user WITH ROLLBACK IMMEDIATE
GO