version: "2"

services:

  mariadb:
    image: linuxserver/mariadb
    container_name: nextcloud_mariadb
    volumes:
      - ./mariadb:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=P@ssw0rd    
    restart: unless-stopped

  nextcloud:
    depends_on:
      - mariadb
    image: linuxserver/nextcloud
    container_name: nextcloud
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8088:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai    
    links:
      - mariadb:mariadb
    restart: unless-stopped