apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: uniworks
spec:
  type: ClusterIP
  ports:
  - name: mssql
    port: 1433
    targetPort: 1433
  selector:
    app: mssql-selector